/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NModal: typeof import('naive-ui')['NModal']
    Player: typeof import('./components/common/Player.vue')['default']
    PlayerControls: typeof import('./components/player/PlayerControls.vue')['default']
    PlayerInfo: typeof import('./components/player/PlayerInfo.vue')['default']
    PlayerProgress: typeof import('./components/player/PlayerProgress.vue')['default']
    PlayerVolume: typeof import('./components/player/PlayerVolume.vue')['default']
    PlaylistPanel: typeof import('./components/common/PlaylistPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
  }
}
